-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer_data
(
    customer_id integer,
    home_store integer,
    customer_phone_number character varying COLLATE pg_catalog."default",
    customer_since character varying COLLATE pg_catalog."default",
    loyalty_card_number character varying COLLATE pg_catalog."default",
    birthdate character varying COLLATE pg_catalog."default",
    gender character varying COLLATE pg_catalog."default",
    birth_year integer,
    usia integer
);

CREATE TABLE IF NOT EXISTS public.outlet_data
(
    sales_outlet_id integer,
    sales_outlet_type character varying COLLATE pg_catalog."default",
    store_square_feet integer,
    store_address character varying COLLATE pg_catalog."default",
    store_city character varying COLLATE pg_catalog."default",
    store_state_province character varying COLLATE pg_catalog."default",
    store_telephone character varying COLLATE pg_catalog."default",
    store_postal_code integer,
    store_longitude double precision,
    store_latitude double precision,
    manager double precision
);

CREATE TABLE IF NOT EXISTS public.product_data
(
    product_id integer,
    product_group character varying COLLATE pg_catalog."default",
    product_category character varying COLLATE pg_catalog."default",
    product_type character varying COLLATE pg_catalog."default",
    product character varying COLLATE pg_catalog."default",
    product_description character varying COLLATE pg_catalog."default",
    unit_of_measure character varying COLLATE pg_catalog."default",
    current_wholesale_price integer,
    current_retail_price integer,
    tax_exempt_yn character varying COLLATE pg_catalog."default",
    promo_yn character varying COLLATE pg_catalog."default",
    new_product_yn character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.staff_data
(
    staff_id integer,
    "position" character varying COLLATE pg_catalog."default",
    start_date character varying COLLATE pg_catalog."default",
    location character varying COLLATE pg_catalog."default",
    nama_staff text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.transaction_data
(
    transaction_id integer,
    transaction_date date,
    transaction_time character varying COLLATE pg_catalog."default",
    sales_outlet_id integer,
    staff_id integer,
    customer_id integer,
    instore_yn character varying COLLATE pg_catalog."default",
    order_ integer,
    line_item_id integer,
    product_id integer,
    quantity integer,
    line_item_amount double precision,
    unit_price double precision,
    promo_item_yn character varying COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public.transaction_data
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.staff_data (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction_data
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customer_data (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction_data
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product_data (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaction_data
    ADD FOREIGN KEY (sales_outlet_id)
    REFERENCES public.outlet_data (sales_outlet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;